filebeat.inputs:
  - type: log
    paths:
      - '/usr/share/filebeat/wso2-logs/*.log'
    processors:
      - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "wso2-logs-%{+yyyy.MM.dd}"

setup.template.name: "wso2-logs"
setup.template.pattern: "wso2-logs-*"
setup.ilm.enabled: false